### ISSUE TITLE
TODO 개발 팀

### ISSUE THREAD

**Issue by Manicarus** [Manicarus/Wine#3]
- [ ] Hub Activity 설계 - 강승원
- [ ] Calendar Activity 설계 - 황준원
- [ ] TimeTable Activity 설계 - 안도언
- [ ] Diet Activity 설계 - 강승원
- [ ] Student ID Barcode Activity - 강승원 (식단이랑 합쳐질 수 있음)
- [ ] Library Activity 설계  

~~추가바람~~

**Comment by Manicarus** [comment]
@yoonki1207 
홍윤기 학생도 다른 사람과 같이해도 되니까 개발에 참여하는 것을 권고합니다.
